### Get all taxpayers

GET http://127.0.0.1:8000/api/v1/taxpayer/

### Crear un nuevo Contribuyente
POST http://127.0.0.1:8000/api/v1/taxpayer/
Content-Type: application/json

{
    "code":29285856,
    "dni": 29285856,
    "name":"xx",
    "address":"La esquina de la casa de Martin",
    "city_address":"SAN JOSE, MISIONES"
}

### Crear un nuevo Contribuyente con codigo en el dni
POST http://127.0.0.1:8000/api/v1/taxpayer/
Content-Type: application/json

{
    "code":29285857,
    "dni": "nd",
    "name":"xx",
    "address":"La esquina de la casa de Martin",
    "city_address":"SAN JOSE, MISIONES"
}

### Delete 'deactive' taxpayer

DELETE http://127.0.0.1:8000/api/v1/taxpayer/2/

### Activate taxpayer

PATCH http://127.0.0.1:8000/api/v1/taxpayer/1/
Content-Type: application/json

{
    "dni": 29285854
}